# Generated by Codex on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reunioes", "0022_enderecoempresamotoboy_participante_whatsapp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rotaparada",
            name="empresa",
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
