# Generated by Django 6.0.8 on 2026-09-08 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0026_chamadoti'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadoti',
            name='aberto_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chamadoti',
            name='atendimento_iniciado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamadoti',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamadoti',
            name='tempo_atendimento_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamadoti',
            name='descricao',
            field=models.TextField(verbose_name='Descrição da solicitação'),
        ),
        migrations.AlterField(
            model_name='chamadoti',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=12),
        ),
        migrations.AlterField(
            model_name='chamadoti',
            name='solucao',
            field=models.TextField(blank=True, verbose_name='Solução aplicada'),
        ),
        migrations.AlterField(
            model_name='chamadoti',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO', 'Aguardando'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=15),
        ),
    ]
