# Generated by Django 6.0.8 on 2026-09-08 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0027_chamadoti_aberto_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadoti',
            name='anexo_imagem',
            field=models.FileField(blank=True, upload_to='chamados_ti/'),
        ),
        migrations.CreateModel(
            name='ConfiguracaoChamadosTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails_notificacao_abertura', models.TextField(default='junior@falavinhacontabil.com.br\nbruno.ares@falavinhacontabil.com.br', help_text='Informe um e-mail por linha, separados por virgula ou ponto e virgula.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_chamados_ti_atualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de chamados TI',
                'verbose_name_plural': 'Configurações de chamados TI',
            },
        ),
    ]
